# -*- coding: utf-8 -*-
"""contact_angle

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ioh8SgqJXwRvxZm2AaLjyxuNM_wkyj5D
"""

import numpy as np
from scipy.optimize import least_squares
import matplotlib.pyplot as plt

# =========================================================
# 円フィット
# =========================================================

def calc_R(xc, zc, x, z):
    return np.sqrt((x - xc)**2 + (z - zc)**2)


def residuals(c, x, z):
    xc, zc, R = c
    return calc_R(xc, zc, x, z) - R


def fit_circle(x, z):

    xc0 = np.mean(x)
    zc0 = np.mean(z)

    R0 = np.mean(np.sqrt((x - xc0)**2 + (z - zc0)**2))

    result = least_squares(
        residuals,
        [xc0, zc0, R0],
        args=(x, z)
    )

    return result.x


# =========================================================
# メイン
# =========================================================

if __name__ == "__main__":

    # -----------------------------------------------------
    # ダミー液滴
    # -----------------------------------------------------

    theta = np.linspace(0, np.pi, 200)

    R_true = 5.0
    xc_true = 2.0
    zc_true = -2.0

    x = xc_true + R_true*np.cos(theta)
    z = zc_true + R_true*np.sin(theta)

    # MD/DPDノイズ
    x += 0.03*np.random.randn(len(x))
    z += 0.03*np.random.randn(len(z))

    # -----------------------------------------------------
    # 基板
    # -----------------------------------------------------

    z_substrate = 0.0

    # -----------------------------------------------------
    # 基板近傍を除外
    # -----------------------------------------------------

    fit_cut = z_substrate + 1.0

    mask = z > fit_cut

    x_fit = x[mask]
    z_fit = z[mask]

    # -----------------------------------------------------
    # 円フィット
    # -----------------------------------------------------

    xc, zc, R = fit_circle(x_fit, z_fit)

    print(f"Center : ({xc:.4f}, {zc:.4f})")
    print(f"Radius : {R:.4f}")

    # -----------------------------------------------------
    # 接触点
    # -----------------------------------------------------

    d = z_substrate - zc

    if abs(d) >= R:
        raise ValueError("円が基板と交わっていません")

    dx = np.sqrt(R**2 - d**2)

    # 右側接触点
    x_contact = xc + dx
    z_contact = z_substrate

    # -----------------------------------------------------
    # 接触角
    # -----------------------------------------------------

    cos_theta = (zc - z_substrate)/R

    cos_theta = np.clip(cos_theta, -1.0, 1.0)

    theta_rad = np.arccos(cos_theta)
    theta_deg = np.degrees(theta_rad)

    print(f"Contact angle = {theta_deg:.2f} deg")

    # -----------------------------------------------------
    # 接線
    # -----------------------------------------------------

    dx_r = x_contact - xc
    dz_r = z_contact - zc

    if abs(dz_r) < 1e-12:
        slope = np.inf
    else:
        slope = -dx_r/dz_r

    # -----------------------------------------------------
    # 描画
    # -----------------------------------------------------

    plt.figure(figsize=(8, 8))

    # 元データ
    plt.scatter(
        x,
        z,
        s=15,
        c="black",
        label="Interface points"
    )

    # フィット使用点
    plt.scatter(
        x_fit,
        z_fit,
        s=15,
        c="red",
        label="Fitting points"
    )

    # フィット円
    t = np.linspace(0, 2*np.pi, 500)

    plt.plot(
        xc + R*np.cos(t),
        zc + R*np.sin(t),
        lw=2,
        label="Circle fit"
    )

    # 基板
    plt.axhline(
        z_substrate,
        color="blue",
        lw=2,
        label="Substrate"
    )

    # 円中心
    plt.scatter(
        xc,
        zc,
        color="magenta",
        s=80,
        label="Center"
    )

    # 接触点
    plt.scatter(
        x_contact,
        z_contact,
        color="green",
        s=80,
        zorder=10,
        label="Contact point"
    )

    # 法線
    plt.plot(
        [xc, x_contact],
        [zc, z_contact],
        "--",
        color="orange",
        lw=2,
        label="Radius"
    )

    # 接線
    if np.isfinite(slope):

        L = 3.0

        xx = np.linspace(
            x_contact - L,
            x_contact + L,
            100
        )

        zz = slope*(xx - x_contact) + z_contact

        plt.plot(
            xx,
            zz,
            color="green",
            lw=2,
            label="Tangent"
        )

    # 接触角表示
    plt.text(
        x_contact - 3,
        0.6,
        f"$\\theta$ = {theta_deg:.1f}^\\circ$",
        fontsize=14
    )

    plt.gca().set_aspect("equal")

    plt.xlabel("x")
    plt.ylabel("z")

    plt.title("Contact Angle from Circle Fitting")

    plt.grid(True)
    plt.legend()

    plt.show()